Lenvendo\UserInteraction\RequestData\BookmarkData:
    properties:
        url:
          - Url:
              message: The url "{{ value }}" is not a valid url.
          - NotBlank: ~
          - Lenvendo\UserInteraction\Validator\Constraint\BookmarkUniqueUrl: ~