Lenvendo\UserInteraction\RequestData\AddBookmarkDtp:
    properties:
        url:
          - Url:
              message: The url "{{ value }}" is not a valid url.
          - NotBlank: ~
          - Lenvendo\UserInteraction\Validator\Constraint\BookmarkUniqueUrl: ~
          - Lenvendo\UserInteraction\Validator\Constraint\BookmarkValidResource: ~

Lenvendo\UserInteraction\RequestData\RemoveBookmarkDto:
    properties:
        password:
          - NotBlank: ~
          - Symfony\Component\Security\Core\Validator\Constraints\UserPassword: ~
        id:
          - NotBlank: ~