bookmarks:
    path: /
    controller: Lenvendo\UserInteraction\Controller\BookmarkController::listAction
    methods: GET

bookmark_add:
    path: /add
    controller: Lenvendo\UserInteraction\Controller\BookmarkController::addAction
    methods: GET|POST

bookmark_remove:
    path: /remove/{bookmark_id}
    controller: Lenvendo\UserInteraction\Controller\BookmarkController::removeAction
    methods: GET|POST

bookmark_item:
    path: /bookmark/{bookmark_id}
    controller: Lenvendo\UserInteraction\Controller\BookmarkController::itemAction
    methods: GET|DELETE
